### ISSUE TITLE
error at artisan step

### ISSUE THREAD

**Issue by reshamas** [M165437/gh-traffic#4]
Is it possible to update instructions for someone who only knows Python?  I tried setting up and got errors when typing `php artisan key:generate`  
```bash
% php artisan key:generate

Warning: require(/Users/reshamashaikh/ds/my_repos/gh-traffic/vendor/autoload.php): failed to open stream: No such file or directory in /Users/reshamashaikh/ds/my_repos/gh-traffic/artisan on line 18

Fatal error: require(): Failed opening required '/Users/reshamashaikh/ds/my_repos/gh-traffic/vendor/autoload.php' (include_path='.:') in /Users/reshamashaikh/ds/my_repos/gh-traffic/artisan on line 18
% 
```

Were we to edit the `artisan` file?

**Comment by M165437** [comment]
Did you install the dependencies? `composer install && npm install`
Do you see a `/vendor` directory in the root of the project?

**Comment by reshamas** [comment]
ok, looks like I need to update my version of PHP.  
I haven't updated to Sierra OS on my Mac yet; wanted to avoid any unwelcome glitches that would bring.

**Comment by M165437** [comment]
I know what you mean. :-) Although, it's not a bad idea to keep the OS current. I will close this issue as the problem does not lie with the project.
